import { NewsItem } from '@/lib/types/news';
import { Race } from '@/lib/types/race';
import { Driver } from '@/lib/types/driver';
import { Team } from '@/lib/types/team';
import { Video } from '@/lib/types/video';
import { Story } from '@/lib/types/story';

// =========================
// Mock Races - Lịch Đua F1 2025 (24 Chặng)
// =========================
export const mockRacesSimple: Race[] = [
  {
    id: '1',
    name: 'Australian Grand Prix',
    date: '2025-03-14',
    location: 'Melbourne, Australia',
    flag: '🇦🇺',
    round: 1,
    status: 'finished',
  },
  {
    id: '2',
    name: 'Chinese Grand Prix',
    date: '2025-03-21',
    location: 'Shanghai, China',
    flag: '🇨🇳',
    round: 2,
    status: 'finished',
  },
  {
    id: '3',
    name: 'Japanese Grand Prix',
    date: '2025-04-04',
    location: 'Suzuka, Japan',
    flag: '🇯🇵',
    round: 3,
    status: 'finished',
  },
  {
    id: '4',
    name: 'Bahrain Grand Prix',
    date: '2025-04-11',
    location: 'Sakhir, Bahrain',
    flag: '🇧🇭',
    round: 4,
    status: 'finished',
  },
  {
    id: '5',
    name: 'Saudi Arabian Grand Prix',
    date: '2025-04-18',
    location: 'Jeddah, Saudi Arabia',
    flag: '🇸🇦',
    round: 5,
    status: 'finished',
  },
  {
    id: '6',
    name: 'Miami Grand Prix',
    date: '2025-05-02',
    location: 'Miami, USA',
    flag: '🇺🇸',
    round: 6,
    status: 'finished',
  },
  {
    id: '7',
    name: 'Emilia-Romagna Grand Prix',
    date: '2025-05-16',
    location: 'Imola, Italy',
    flag: '🇮🇹',
    round: 7,
    status: 'finished',
  },
  {
    id: '8',
    name: 'Monaco Grand Prix',
    date: '2025-05-23',
    location: 'Monte Carlo, Monaco',
    flag: '🇲🇨',
    round: 8,
    status: 'finished',
  },
  {
    id: '9',
    name: 'Spanish Grand Prix',
    date: '2025-05-30',
    location: 'Barcelona, Spain',
    flag: '🇪🇸',
    round: 9,
    status: 'finished',
  },
  {
    id: '10',
    name: 'Canadian Grand Prix',
    date: '2025-06-13',
    location: 'Montreal, Canada',
    flag: '🇨🇦',
    round: 10,
    status: 'finished',
  },
  {
    id: '11',
    name: 'Austrian Grand Prix',
    date: '2025-06-27',
    location: 'Spielberg, Austria',
    flag: '🇦🇹',
    round: 11,
    status: 'finished',
  },
  {
    id: '12',
    name: 'British Grand Prix',
    date: '2025-07-04',
    location: 'Silverstone, UK',
    flag: '🇬🇧',
    round: 12,
    status: 'finished',
  },
  {
    id: '13',
    name: 'Belgian Grand Prix',
    date: '2025-07-25',
    location: 'Spa, Belgium',
    flag: '🇧🇪',
    round: 13,
    status: 'finished',
  },
  {
    id: '14',
    name: 'Hungarian Grand Prix',
    date: '2025-08-01',
    location: 'Budapest, Hungary',
    flag: '🇭🇺',
    round: 14,
    status: 'finished',
  },
  {
    id: '15',
    name: 'Dutch Grand Prix',
    date: '2025-08-29',
    location: 'Zandvoort, Netherlands',
    flag: '🇳🇱',
    round: 15,
    status: 'finished',
  },
  {
    id: '16',
    name: 'Italian Grand Prix',
    date: '2025-09-05',
    location: 'Monza, Italy',
    flag: '🇮🇹',
    round: 16,
    status: 'finished',
  },
  {
    id: '17',
    name: 'Azerbaijan Grand Prix',
    date: '2025-09-19',
    location: 'Baku, Azerbaijan',
    flag: '🇦🇿',
    round: 17,
    status: 'finished',
  },
  {
    id: '18',
    name: 'Singapore Grand Prix',
    date: '2025-10-03',
    location: 'Singapore, Singapore',
    flag: '🇸🇬',
    round: 18,
    status: 'upcoming',
  },
  {
    id: '19',
    name: 'United States Grand Prix',
    date: '2025-10-17',
    location: 'Austin, USA',
    flag: '🇺🇸',
    round: 19,
    status: 'upcoming',
  },
  {
    id: '20',
    name: 'Mexico City Grand Prix',
    date: '2025-10-24',
    location: 'Mexico City, Mexico',
    flag: '🇲🇽',
    round: 20,
    status: 'upcoming',
  },
  {
    id: '21',
    name: 'Brazilian Grand Prix',
    date: '2025-11-07',
    location: 'Sao Paulo, Brazil',
    flag: '🇧🇷',
    round: 21,
    status: 'upcoming',
  },
  {
    id: '22',
    name: 'Las Vegas Grand Prix',
    date: '2025-11-20',
    location: 'Las Vegas, USA',
    flag: '🇺🇸',
    round: 22,
    status: 'upcoming',
  },
  {
    id: '23',
    name: 'Qatar Grand Prix',
    date: '2025-11-28',
    location: 'Lusail, Qatar',
    flag: '🇶🇦',
    round: 23,
    status: 'upcoming',
  },
  {
    id: '24',
    name: 'Abu Dhabi Grand Prix',
    date: '2025-12-05',
    location: 'Yas Island, UAE',
    flag: '🇦🇪',
    round: 24,
    status: 'upcoming',
  },
];

export const mockRacesDetailed: Race[] = [
  {
    id: '1',
    name: 'Australian Grand Prix',
    date: '2025-03-14',
    location: 'Melbourne, Australia',
    flag: '🇦🇺',
    round: 1,
    status: 'finished',
    circuit: 'Albert Park Circuit',
    laps: 57,
    distance: '307.574 km',
    winner: 'Lando Norris',
    team: 'McLaren',
    time: '1:42:06.304',
  },
  {
    id: '2',
    name: 'Chinese Grand Prix',
    date: '2025-03-21',
    location: 'Shanghai, China',
    flag: '🇨🇳',
    round: 2,
    status: 'finished',
    circuit: 'Shanghai International Circuit',
    laps: 56,
    distance: '305.066 km',
    winner: 'Oscar Piastri',
    team: 'McLaren',
    time: '1:30:55.026',
  },
  {
    id: '3',
    name: 'Japanese Grand Prix',
    date: '2025-04-04',
    location: 'Suzuka, Japan',
    flag: '🇯🇵',
    round: 3,
    status: 'finished',
    circuit: 'Suzuka International Racing Course',
    laps: 53,
    distance: '307.471 km',
    winner: 'Max Verstappen',
    team: 'Red Bull Racing',
    time: '1:22:06.983',
  },
  {
    id: '4',
    name: 'Bahrain Grand Prix',
    date: '2025-04-11',
    location: 'Sakhir, Bahrain',
    flag: '🇧🇭',
    round: 4,
    status: 'finished',
    circuit: 'Bahrain International Circuit',
    laps: 57,
    distance: '308.238 km',
    winner: 'Oscar Piastri',
    team: 'McLaren',
    time: '1:35:39.435',
  },
  {
    id: '5',
    name: 'Saudi Arabian Grand Prix',
    date: '2025-04-18',
    location: 'Jeddah, Saudi Arabia',
    flag: '🇸🇦',
    round: 5,
    status: 'finished',
    circuit: 'Jeddah Corniche Circuit',
    laps: 50,
    distance: '308.452 km',
    winner: 'Oscar Piastri',
    team: 'McLaren',
    time: '1:21:06.758',
  },
  {
    id: '6',
    name: 'Miami Grand Prix',
    date: '2025-05-02',
    location: 'Miami, USA',
    flag: '🇺🇸',
    round: 6,
    status: 'finished',
    circuit: 'Miami International Autodrome',
    laps: 57,
    distance: '309.266 km',
    winner: 'Oscar Piastri',
    team: 'McLaren',
    time: '1:28:51.587',
  },
  {
    id: '7',
    name: 'Emilia-Romagna Grand Prix',
    date: '2025-05-16',
    location: 'Imola, Italy',
    flag: '🇮🇹',
    round: 7,
    status: 'finished',
    circuit: 'Autodromo Enzo e Dino Ferrari',
    laps: 63,
    distance: '309.049 km',
    winner: 'Max Verstappen',
    team: 'Red Bull Racing',
    time: '1:31:33.199',
  },
  {
    id: '8',
    name: 'Monaco Grand Prix',
    date: '2025-05-23',
    location: 'Monte Carlo, Monaco',
    flag: '🇲🇨',
    round: 8,
    status: 'finished',
    circuit: 'Circuit de Monaco',
    laps: 78,
    distance: '260.286 km',
    winner: 'Lando Norris',
    team: 'McLaren',
    time: '1:40:33.843',
  },
  {
    id: '9',
    name: 'Spanish Grand Prix',
    date: '2025-05-30',
    location: 'Barcelona, Spain',
    flag: '🇪🇸',
    round: 9,
    status: 'finished',
    circuit: 'Circuit de Barcelona-Catalunya',
    laps: 66,
    distance: '307.023 km',
    winner: 'Oscar Piastri',
    team: 'McLaren',
    time: '1:32:57.375',
  },
  {
    id: '10',
    name: 'Canadian Grand Prix',
    date: '2025-06-13',
    location: 'Montreal, Canada',
    flag: '🇨🇦',
    round: 10,
    status: 'finished',
    circuit: 'Circuit Gilles Villeneuve',
    laps: 70,
    distance: '305.270 km',
    winner: 'George Russell',
    team: 'Mercedes',
    time: '1:31:52.688',
  },
  {
    id: '11',
    name: 'Austrian Grand Prix',
    date: '2025-06-27',
    location: 'Spielberg, Austria',
    flag: '🇦🇹',
    round: 11,
    status: 'finished',
    circuit: 'Red Bull Ring',
    laps: 71,
    distance: '306.452 km',
    winner: 'Lando Norris',
    team: 'McLaren',
    time: '1:23:47.693',
  },
  {
    id: '12',
    name: 'British Grand Prix',
    date: '2025-07-04',
    location: 'Silverstone, UK',
    flag: '🇬🇧',
    round: 12,
    status: 'finished',
    circuit: 'Silverstone Circuit',
    laps: 52,
    distance: '306.198 km',
    winner: 'Lando Norris',
    team: 'McLaren',
    time: '1:37:15.735',
  },
  {
    id: '13',
    name: 'Belgian Grand Prix',
    date: '2025-07-25',
    location: 'Spa, Belgium',
    flag: '🇧🇪',
    round: 13,
    status: 'finished',
    circuit: 'Circuit de Spa-Francorchamps',
    laps: 44,
    distance: '308.052 km',
    winner: 'Oscar Piastri',
    team: 'McLaren',
    time: '1:25:22.601',
  },
  {
    id: '14',
    name: 'Hungarian Grand Prix',
    date: '2025-08-01',
    location: 'Budapest, Hungary',
    flag: '🇭🇺',
    round: 14,
    status: 'finished',
    circuit: 'Hungaroring',
    laps: 70,
    distance: '306.630 km',
    winner: 'Lando Norris',
    team: 'McLaren',
    time: '1:35:21.231',
  },
  {
    id: '15',
    name: 'Dutch Grand Prix',
    date: '2025-08-29',
    location: 'Zandvoort, Netherlands',
    flag: '🇳🇱',
    round: 15,
    status: 'finished',
    circuit: 'Circuit Zandvoort',
    laps: 72,
    distance: '306.587 km',
    winner: 'Oscar Piastri',
    team: 'McLaren',
    time: '1:38:29.849',
  },
  {
    id: '16',
    name: 'Italian Grand Prix',
    date: '2025-09-05',
    location: 'Monza, Italy',
    flag: '🇮🇹',
    round: 16,
    status: 'finished',
    circuit: 'Autodromo Nazionale di Monza',
    laps: 53,
    distance: '306.720 km',
    winner: 'Max Verstappen',
    team: 'Red Bull Racing',
    time: '1:13:24.325',
  },
  {
    id: '17',
    name: 'Azerbaijan Grand Prix',
    date: '2025-09-19',
    location: 'Baku, Azerbaijan',
    flag: '🇦🇿',
    round: 17,
    status: 'finished',
    circuit: 'Baku City Circuit',
    laps: 51,
    distance: '306.049 km',
    winner: 'Max Verstappen',
    team: 'Red Bull Racing',
    time: '1:33:26.408',
  },
  {
    id: '18',
    name: 'Singapore Grand Prix',
    date: '2025-10-03',
    location: 'Singapore, Singapore',
    flag: '🇸🇬',
    round: 18,
    status: 'upcoming',
    circuit: 'Marina Bay Street Circuit',
    laps: 61,
    distance: '308.706 km',
  },
  {
    id: '19',
    name: 'United States Grand Prix',
    date: '2025-10-17',
    location: 'Austin, USA',
    flag: '🇺🇸',
    round: 19,
    status: 'upcoming',
    circuit: 'Circuit of the Americas',
    laps: 56,
    distance: '308.405 km',
  },
  {
    id: '20',
    name: 'Mexico City Grand Prix',
    date: '2025-10-24',
    location: 'Mexico City, Mexico',
    flag: '🇲🇽',
    round: 20,
    status: 'upcoming',
    circuit: 'Autódromo Hermanos Rodríguez',
    laps: 71,
    distance: '305.354 km',
  },
  {
    id: '21',
    name: 'Brazilian Grand Prix',
    date: '2025-11-07',
    location: 'Sao Paulo, Brazil',
    flag: '🇧🇷',
    round: 21,
    status: 'upcoming',
    circuit: 'Interlagos',
    laps: 71,
    distance: '305.879 km',
  },
  {
    id: '22',
    name: 'Las Vegas Grand Prix',
    date: '2025-11-20',
    location: 'Las Vegas, USA',
    flag: '🇺🇸',
    round: 22,
    status: 'upcoming',
    circuit: 'Las Vegas Strip Circuit',
    laps: 50,
    distance: '260.7 km',
  },
  {
    id: '23',
    name: 'Qatar Grand Prix',
    date: '2025-11-28',
    location: 'Lusail, Qatar',
    flag: '🇶🇦',
    round: 23,
    status: 'upcoming',
    circuit: 'Lusail International Circuit',
    laps: 57,
    distance: '308.238 km',
  },
  {
    id: '24',
    name: 'Abu Dhabi Grand Prix',
    date: '2025-12-05',
    location: 'Yas Island, UAE',
    flag: '🇦🇪',
    round: 24,
    status: 'upcoming',
    circuit: 'Yas Marina Circuit',
    laps: 58,
    distance: '306.183 km',
  },
];

// =========================
// Mock Drivers - 20 Tay Đua Hiện Có
// =========================
export const mockDriversSimple: Driver[] = [
  {
    id: 'norris',
    name: 'Lando Norris',
    country: 'UK',
    teamId: 'mclaren',
    image: '/images/drivers/norris.png',
  },
  {
    id: 'piastri',
    name: 'Oscar Piastri',
    country: 'Australia',
    teamId: 'mclaren',
    image: '/images/drivers/piastri.png',
  },
  {
    id: 'verstappen',
    name: 'Max Verstappen',
    country: 'Netherlands',
    teamId: 'redbull',
    image: '/images/drivers/verstappen.png',
  },
  {
    id: 'lawson',
    name: 'Liam Lawson',
    country: 'New Zealand',
    teamId: 'redbull',
    image: '/images/drivers/lawson.png',
  },
  {
    id: 'leclerc',
    name: 'Charles Leclerc',
    country: 'Monaco',
    teamId: 'ferrari',
    image: '/images/drivers/leclerc.png',
  },
  {
    id: 'hamilton',
    name: 'Lewis Hamilton',
    country: 'UK',
    teamId: 'ferrari',
    image: '/images/drivers/hamilton.png',
  },
  {
    id: 'russell',
    name: 'George Russell',
    country: 'UK',
    teamId: 'mercedes',
    image: '/images/drivers/russell.png',
  },
  {
    id: 'antonelli',
    name: 'Kimi Antonelli',
    country: 'Italy',
    teamId: 'mercedes',
    image: '/images/drivers/antonelli.png',
  },
  {
    id: 'alonso',
    name: 'Fernando Alonso',
    country: 'Spain',
    teamId: 'astonmartin',
    image: '/images/drivers/alonso.png',
  },
  {
    id: 'stroll',
    name: 'Lance Stroll',
    country: 'Canada',
    teamId: 'astonmartin',
    image: '/images/drivers/stroll.png',
  },
  {
    id: 'ocon',
    name: 'Esteban Ocon',
    country: 'France',
    teamId: 'haas',
    image: '/images/drivers/ocon.png',
  },
  {
    id: 'bearman',
    name: 'Oliver Bearman',
    country: 'UK',
    teamId: 'haas',
    image: '/images/drivers/bearman.png',
  },
  {
    id: 'gasly',
    name: 'Pierre Gasly',
    country: 'France',
    teamId: 'alpine',
    image: '/images/drivers/gasly.png',
  },
  {
    id: 'doohan',
    name: 'Jack Doohan',
    country: 'Australia',
    teamId: 'alpine',
    image: '/images/drivers/doohan.png',
  },
  {
    id: 'albon',
    name: 'Alexander Albon',
    country: 'Thailand',
    teamId: 'williams',
    image: '/images/drivers/albon.png',
  },
  {
    id: 'sainz',
    name: 'Carlos Sainz',
    country: 'Spain',
    teamId: 'williams',
    image: '/images/drivers/sainz.png',
  },
  {
    id: 'tsunoda',
    name: 'Yuki Tsunoda',
    country: 'Japan',
    teamId: 'rb',
    image: '/images/drivers/tsunoda.png',
  },
  {
    id: 'hadjar',
    name: 'Isack Hadjar',
    country: 'France',
    teamId: 'rb',
    image: '/images/drivers/hadjar.png',
  },
  {
    id: 'bottas',
    name: 'Valtteri Bottas',
    country: 'Finland',
    teamId: 'sauber',
    image: '/images/drivers/bottas.png',
  },
  {
    id: 'bortoleto',
    name: 'Gabriel Bortoleto',
    country: 'Brazil',
    teamId: 'sauber',
    image: '/images/drivers/bortoleto.png',
  },
];

// duplicate mockDriversDetailed removed (kept earlier declaration)

export const mockDriversDetailed: Driver[] = [
  {
    id: 'norris',
    name: 'Lando Norris',
    country: 'UK',
    teamId: 'mclaren',
    image: '/images/drivers/norris.png',
    number: 4,
    podiums: 15,
    worldChampionships: 0,
    description: "McLaren's lead driver with multiple 2025 wins.",
  },
  {
    id: 'piastri',
    name: 'Oscar Piastri',
    country: 'Australia',
    teamId: 'mclaren',
    image: '/images/drivers/piastri.png',
    number: 81,
    podiums: 10,
    worldChampionships: 0,
    description: "Rookie sensation leading McLaren's 2025 charge.",
  },
  {
    id: 'verstappen',
    name: 'Max Verstappen',
    country: 'Netherlands',
    teamId: 'redbull',
    image: '/images/drivers/verstappen.png',
    number: 1,
    podiums: 103,
    worldChampionships: 4,
    description: 'Defending champion defending Red Bull in 2025.',
  },
  {
    id: 'lawson',
    name: 'Liam Lawson',
    country: 'New Zealand',
    teamId: 'redbull',
    image: '/images/drivers/lawson.png',
    number: 30,
    podiums: 0,
    worldChampionships: 0,
    description: "Red Bull's rising star for 2025.",
  },
  {
    id: 'leclerc',
    name: 'Charles Leclerc',
    country: 'Monaco',
    teamId: 'ferrari',
    image: '/images/drivers/leclerc.png',
    number: 16,
    podiums: 30,
    worldChampionships: 0,
    description: "Ferrari's lead driver with Hamilton in 2025.",
  },
  {
    id: 'hamilton',
    name: 'Lewis Hamilton',
    country: 'UK',
    teamId: 'ferrari',
    image: '/images/drivers/hamilton.png',
    number: 44,
    podiums: 197,
    worldChampionships: 7,
    description: 'Seven-time champion joining Ferrari in 2025.',
  },
  {
    id: 'russell',
    name: 'George Russell',
    country: 'UK',
    teamId: 'mercedes',
    image: '/images/drivers/russell.png',
    number: 63,
    podiums: 35,
    worldChampionships: 0,
    description: "Mercedes' lead driver with Antonelli in 2025.",
  },
  {
    id: 'antonelli',
    name: 'Andrea Kimi Antonelli',
    country: 'Italy',
    teamId: 'mercedes',
    image: '/images/drivers/antonelli.png',
    number: 12,
    podiums: 0,
    worldChampionships: 0,
    description: "Mercedes' promising rookie for 2025.",
  },
  {
    id: 'alonso',
    name: 'Fernando Alonso',
    country: 'Spain',
    teamId: 'astonmartin',
    image: '/images/drivers/alonso.png',
    number: 14,
    podiums: 106,
    worldChampionships: 2,
    description: 'Veteran leader for Aston Martin in 2025.',
  },
  {
    id: 'stroll',
    name: 'Lance Stroll',
    country: 'Canada',
    teamId: 'astonmartin',
    image: '/images/drivers/stroll.png',
    number: 18,
    podiums: 10,
    worldChampionships: 0,
    description: "Aston Martin's second driver.",
  },
  {
    id: 'ocon',
    name: 'Esteban Ocon',
    country: 'France',
    teamId: 'haas',
    image: '/images/drivers/ocon.png',
    number: 31,
    podiums: 2,
    worldChampionships: 0,
    description: 'Experienced driver for Haas in 2025.',
  },
  {
    id: 'bearman',
    name: 'Oliver Bearman',
    country: 'UK',
    teamId: 'haas',
    image: '/images/drivers/bearman.png',
    number: 87,
    podiums: 0,
    worldChampionships: 0,
    description: "Haas' promising rookie for 2025.",
  },
  {
    id: 'gasly',
    name: 'Pierre Gasly',
    country: 'France',
    teamId: 'alpine',
    image: '/images/drivers/gasly.png',
    number: 10,
    podiums: 3,
    worldChampionships: 0,
    description: "Alpine's experienced driver.",
  },
  {
    id: 'doohan',
    name: 'Jack Doohan',
    country: 'Australia',
    teamId: 'alpine',
    image: '/images/drivers/doohan.png',
    number: 14,
    podiums: 0,
    worldChampionships: 0,
    description: "Alpine's rookie for 2025.",
  },
  {
    id: 'albon',
    name: 'Alexander Albon',
    country: 'Thailand',
    teamId: 'williams',
    image: '/images/drivers/albon.png',
    number: 23,
    podiums: 2,
    worldChampionships: 0,
    description: "Williams' lead driver.",
  },
  {
    id: 'sainz',
    name: 'Carlos Sainz',
    country: 'Spain',
    teamId: 'williams',
    image: '/images/drivers/sainz.png',
    number: 55,
    podiums: 22,
    worldChampionships: 0,
    description: 'Former Ferrari driver joining Williams in 2025.',
  },
  {
    id: 'tsunoda',
    name: 'Yuki Tsunoda',
    country: 'Japan',
    teamId: 'rb',
    image: '/images/drivers/tsunoda.png',
    number: 22,
    podiums: 0,
    worldChampionships: 0,
    description: "RB's lead driver.",
  },
  {
    id: 'hadjar',
    name: 'Isack Hadjar',
    country: 'France',
    teamId: 'rb',
    image: '/images/drivers/hadjar.png',
    number: 6,
    podiums: 0,
    worldChampionships: 0,
    description: "RB's rookie for 2025.",
  },
  {
    id: 'bottas',
    name: 'Valtteri Bottas',
    country: 'Finland',
    teamId: 'sauber',
    image: '/images/drivers/bottas.png',
    number: 77,
    podiums: 67,
    worldChampionships: 0,
    description: "Sauber's veteran driver.",
  },
  {
    id: 'bortoleto',
    name: 'Gabriel Bortoleto',
    country: 'Brazil',
    teamId: 'sauber',
    image: '/images/drivers/bortoleto.png',
    number: 5,
    podiums: 0,
    worldChampionships: 0,
    description: "Sauber's rookie for 2025.",
  },
  {
    id: 'hulkenberg',
    name: 'Nico Hülkenberg',
    country: 'Germany',
    teamId: 'sauber',
    image: '/images/drivers/hulkenberg.png',
    number: 27,
    podiums: 0,
    worldChampionships: 0,
    description: 'Returning to Sauber in 2025.',
  },
  {
    id: 'magnussen',
    name: 'Kevin Magnussen',
    country: 'Denmark',
    teamId: 'haas',
    image: '/images/drivers/magnussen.png',
    number: 20,
    podiums: 1,
    worldChampionships: 0,
    description: "Haas' aggressive driver.",
  },
];

// =========================
// Mock Teams
// =========================
export const mockTeamsSimple: Team[] = [
  {
    id: 'mclaren',
    name: 'McLaren',
    logo: '/images/teams/mclaren.png',
    color: '#FF8000',
    position: 1,
    points: 450,
    drivers: ['norris', 'piastri'],
  },
  {
    id: 'redbull',
    name: 'Red Bull Racing',
    logo: '/images/teams/redbull.png',
    color: '#3671C6',
    position: 2,
    points: 400,
    drivers: ['verstappen', 'lawson'],
  },
  {
    id: 'ferrari',
    name: 'Scuderia Ferrari',
    logo: '/images/teams/ferrari.png',
    color: '#E8002D',
    position: 3,
    points: 350,
    drivers: ['leclerc', 'hamilton'],
  },
  {
    id: 'mercedes',
    name: 'Mercedes-AMG',
    logo: '/images/teams/mercedes.png',
    color: '#27F4D2',
    position: 4,
    points: 300,
    drivers: ['russell', 'antonelli'],
  },
  {
    id: 'astonmartin',
    name: 'Aston Martin',
    logo: '/images/teams/astonmartin.png',
    color: '#006F62',
    position: 5,
    points: 180,
    drivers: ['alonso', 'stroll'],
  },
  {
    id: 'alpine',
    name: 'Alpine',
    logo: '/images/teams/alpine.png',
    color: '#0090FF',
    position: 6,
    points: 120,
    drivers: ['gasly', 'doohan'],
  },
  {
    id: 'williams',
    name: 'Williams',
    logo: '/images/teams/williams.png',
    color: '#00A0DE',
    position: 7,
    points: 70,
    drivers: ['albon', 'sainz'],
  },
  {
    id: 'rb',
    name: 'RB (Visa Cash App RB)',
    logo: '/images/teams/rb.png',
    color: '#2B4562',
    position: 8,
    points: 60,
    drivers: ['tsunoda', 'hadjar'],
  },
  {
    id: 'sauber',
    name: 'Stake F1 Team Kick Sauber',
    logo: '/images/teams/sauber.png',
    color: '#52E252',
    position: 9,
    points: 30,
    drivers: ['bottas', 'bortoleto'],
  },
  {
    id: 'haas',
    name: 'Haas F1 Team',
    logo: '/images/teams/haas.png',
    color: '#B6BABD',
    position: 10,
    points: 20,
    drivers: ['ocon', 'bearman'],
  },
];

export const mockTeamsDetailed: Team[] = [
  {
    id: 'mclaren',
    name: 'McLaren',
    logo: '/images/teams/mclaren.png',
    color: '#FF8000',
    position: 1,
    points: 450,
    drivers: ['norris', 'piastri'],
    base: 'Woking, UK',
    chief: 'Andrea Stella',
    chassis: 'MCL39',
    powerUnit: 'Mercedes',
  },
  {
    id: 'redbull',
    name: 'Red Bull Racing',
    logo: '/images/teams/redbull.png',
    color: '#3671C6',
    position: 2,
    points: 400,
    drivers: ['verstappen', 'lawson'],
    base: 'Milton Keynes, UK',
    chief: 'Christian Horner',
    chassis: 'RB21',
    powerUnit: 'Honda RBPT',
  },
  {
    id: 'ferrari',
    name: 'Scuderia Ferrari',
    logo: '/images/teams/ferrari.png',
    color: '#E8002D',
    position: 3,
    points: 350,
    drivers: ['leclerc', 'hamilton'],
    base: 'Maranello, Italy',
    chief: 'Frédéric Vasseur',
    chassis: 'SF-25',
    powerUnit: 'Ferrari',
  },
  {
    id: 'mercedes',
    name: 'Mercedes-AMG',
    logo: '/images/teams/mercedes.png',
    color: '#27F4D2',
    position: 4,
    points: 300,
    drivers: ['russell', 'antonelli'],
    base: 'Brackley, UK',
    chief: 'Toto Wolff',
    chassis: 'W15',
    powerUnit: 'Mercedes',
  },
  {
    id: 'astonmartin',
    name: 'Aston Martin',
    logo: '/images/teams/astonmartin.png',
    color: '#006F62',
    position: 5,
    points: 180,
    drivers: ['alonso', 'stroll'],
    base: 'Silverstone, UK',
    chief: 'Mike Krack',
    chassis: 'AMR25',
    powerUnit: 'Mercedes',
  },
  {
    id: 'alpine',
    name: 'Alpine',
    logo: '/images/teams/alpine.png',
    color: '#0090FF',
    position: 6,
    points: 120,
    drivers: ['gasly', 'doohan'],
    base: 'Enstone, UK',
    chief: 'Bruno Famin',
    chassis: 'A525',
    powerUnit: 'Renault',
  },
  {
    id: 'williams',
    name: 'Williams',
    logo: '/images/teams/williams.png',
    color: '#00A0DE',
    position: 7,
    points: 70,
    drivers: ['albon', 'sainz'],
    base: 'Grove, UK',
    chief: 'James Vowles',
    chassis: 'FW47',
    powerUnit: 'Mercedes',
  },
  {
    id: 'rb',
    name: 'RB (Visa Cash App RB)',
    logo: '/images/teams/rb.png',
    color: '#2B4562',
    position: 8,
    points: 60,
    drivers: ['tsunoda', 'hadjar'],
    base: 'Faenza, Italy',
    chief: 'Laurent Mekies',
    chassis: 'RB01',
    powerUnit: 'Honda RBPT',
  },
  {
    id: 'sauber',
    name: 'Stake F1 Team Kick Sauber',
    logo: '/images/teams/sauber.png',
    color: '#52E252',
    position: 9,
    points: 30,
    drivers: ['bottas', 'bortoleto'],
    base: 'Hinwil, Switzerland',
    chief: 'Alessandro Alunni Bravi',
    chassis: 'C45',
    powerUnit: 'Ferrari',
  },
  {
    id: 'haas',
    name: 'Haas F1 Team',
    logo: '/images/teams/haas.png',
    color: '#B6BABD',
    position: 10,
    points: 20,
    drivers: ['ocon', 'bearman'],
    base: 'Kannapolis, USA',
    chief: 'Ayao Komatsu',
    chassis: 'VF-25',
    powerUnit: 'Ferrari',
  },
];

// =========================
// Mock News
// =========================
export const mockNewsSimple: NewsItem[] = [
  {
    id: '1',
    title: 'Norris Wins Australian GP 2025',
    image: '/images/news/australia-norris.png',
    date: '2025-03-16',
    category: 'Race',
    href: '/news/norris-australia-2025',
    summary: 'Lando Norris dominates in Melbourne.',
    readTime: '3 min',
  },
  {
    id: '2',
    title: 'Verstappen Secures Azerbaijan Victory',
    image: '/images/news/azerbaijan-verstappen.png',
    date: '2025-09-21',
    category: 'Race',
    href: '/news/verstappen-azerbaijan-2025',
    summary: 'Max Verstappen wins in Baku.',
    readTime: '3 min',
  },
  {
    id: '3',
    title: 'Ferrari Upgrades for Singapore',
    image: '/images/news/ferrari-singapore.png',
    date: '2025-10-01',
    category: 'Tech',
    href: '/news/ferrari-singapore-2025',
    summary: 'New aero package revealed.',
    readTime: '4 min',
  },
];

export const mockNewsDetailed: NewsItem[] = [
  {
    id: '1',
    title: 'Norris Wins Australian GP 2025',
    image: '/images/news/australia-norris.png',
    date: '2025-03-16',
    category: 'Race',
    href: '/news/norris-australia-2025',
    author: 'Tom Clarkson',
    content: 'Lando Norris led from pole to win...',
    summary: 'Lando Norris dominates in Melbourne.',
    readTime: '3 min',
  },
  {
    id: '2',
    title: 'Verstappen Secures Azerbaijan Victory',
    image: '/images/news/azerbaijan-verstappen.png',
    date: '2025-09-21',
    category: 'Race',
    href: '/news/verstappen-azerbaijan-2025',
    author: 'Laura Winter',
    content: 'Max Verstappen fought back to win...',
    summary: 'Max Verstappen wins in Baku.',
    readTime: '3 min',
  },
];

// =========================
// Videos
// =========================
export const mockVideosDetailed: Video[] = [
  {
    id: '1',
    title: 'Highlights: Australian GP 2025',
    thumbnail: '/images/videos/australia-highlights.png',
    duration: '8:30',
    date: '2025-03-16',
    url: 'https://example.com/videos/australia-2025',
    description: "Full highlights of Norris' win.",
  },
  {
    id: '2',
    title: 'Onboard: Verstappen in Azerbaijan',
    thumbnail: '/images/videos/verstappen-azerbaijan.png',
    duration: '6:15',
    date: '2025-09-21',
    url: 'https://example.com/videos/verstappen-azerbaijan',
    description: "Onboard of Verstappen's Baku win.",
  },
];

// =========================
// Stories
// =========================
export const mockStoriesDetailed: Story[] = [
  {
    id: '1',
    title: 'Behind the Scenes at Australian GP',
    image: '/images/stories/australia-behind.png',
    link: '/stories/australia-2025',
    summary: 'Exclusive paddock access.',
    content: 'Interviews with McLaren team...',
  },
  {
    id: '2',
    title: "Red Bull's 2025 Strategy",
    image: '/images/stories/redbull-strategy.png',
    link: '/stories/redbull-2025',
    summary: 'How Red Bull plans to fight back.',
    content: "Analysis of Red Bull's approach...",
  },
];
